language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.2
bundler_args: "--without local"
before_script:
- bundle exec rake app:db:setup
script:
- bundle exec rake test
- bundle exec rake cane
- bundle exec rake rubocop
notifications:
  flowdock:
    secure: hRaeI2fe3mbWP3BbIkurjuLLu7Lbq4ReE0Ee1i4h+drvv+pio6BItuTd7ujlhM80ZkRfpffTOZdk34fbZduf1WB+peWaYfO1f2kDPviap7wdnFRlSpJF/KaDS3/D70zA8RycSC1Oaam34cKoVg1Gmdwl0/EJAsRncfu3I+tYyiA=
env:
  global:
    secure: w/lOREURd+nNeOdLPffnsVT9jwvrp/ougA8a/d2EZJ48pMp1d+5bL83ZwcUfVdDoNq8YEFu+fje8La4LmkdL1GUhnHGmznkVlPnPVMMZE5fenYiJIgkyhDe4EchBXUifT0iH4HjB4SsbaehzPy78H9ceD9qtG2zyCtDhzx0ic/A=
